DROP TABLE students;
DROP TABLE agreement;
DROP TABLE companies;
DROP TABLE staff;
DROP TABLE lresearches;
DROP TABLE pdis;
DROP TABLE addendums;

DROP TYPE PDI_tab FORCE;
DROP TYPE Company_tab FORCE;
DROP TYPE AgreementCol_tab FORCE;
DROP TYPE Agreement_tab FORCE;
DROP TYPE Addendum_tab FORCE;
DROP TYPE RefLResearch_va FORCE;
DROP TYPE RefStaff_va FORCE;
DROP TYPE RefStudent_va FORCE;
DROP TYPE Addendum_ob FORCE;
DROP TYPE Staff_ob FORCE;
DROP TYPE Student_ob FORCE;
DROP TYPE PDI_ob FORCE;
DROP TYPE LResearch_ob FORCE;
DROP TYPE AgreementInt_ob FORCE;
DROP TYPE AgreementCol_ob FORCE;
DROP TYPE Agreement_ob FORCE;
DROP TYPE Company_ob FORCE;
DROP TYPE currentStudiesList FORCE;
DROP TYPE fullName FORCE;